---
title: "Reproducible Research: Peer Assessment 1"
author: "Fallatah K. M."
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading and preprocessing the data  
```{r, echo = TRUE}
library(lubridate)
unzip("activity.zip")
data <- read.csv("activity.csv")
data$date <- ymd(data$date)
```  
## What is mean total number of steps taken per day?  
```{r, echo=TRUE}
data$date <- factor(data$date)
sumsteps <- aggregate(data$steps ~ data$date, FUN = sum)
names(sumsteps) <- c("Date", "Steps")
hist(sumsteps$Steps, main = "Total Steps Taken Each Day", xlab = "Steps")
totalmean <- mean(sumsteps$Steps)
totalmean
totalmedian <- median(sumsteps$Steps)
totalmedian
```  
## What is the average daily activity pattern?  
```{r, echo=TRUE}
library(ggplot2)
intervalsteps <- aggregate(data$steps ~ data$interval, FUN = mean, na.rm = TRUE)
names(intervalsteps) <- c("Interval", "Steps")
ggplot(data = intervalsteps, aes(x=Interval, y=Steps)) + geom_line()
intervalsteps[which.max(intervalsteps$Steps),]
```
## Imputing missing values  
```{r, echo=TRUE}
nas <- data[is.na(data$steps),]
nrow(nas)
for (i in 1:nrow(nas)){
        tmp_interval <- nas[i,"interval"]
        tmp_mean <- intervalsteps[intervalsteps$Interval==tmp_interval,"Steps"]
        nas[i,"steps"] <- tmp_mean
}
filled.data <- data
nasvec <- setNames(nas$steps, rownames(nas))
filled.data[rownames(nas), "steps"] <- nasvec
sumsteps_final <- aggregate(filled.data$steps ~ filled.data$date, FUN = sum)
names(sumsteps_final) <- c("Date", "Steps")
hist(sumsteps_final$Steps, main = "Total Steps Taken Each Day", xlab = "Steps")
finalmean <- mean(sumsteps_final$Steps)
finalmean
finalmedian <- median(sumsteps_final$Steps)
finalmedian
```
Imputing the missing values causes no changes, because the imputed values are the small parts of the mean. (sorry for bad expression)
## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
filled.data$day <- weekdays(as.Date(filled.data$date))
for (i in 1:nrow(filled.data)){
        ifelse(filled.data[i,"day"] == "Saturday"|
                filled.data[i,"day"] == "Sunday", 
                filled.data[i,"day"] <- "Weekend", 
                filled.data[i,"day"] <- "Weekday")
}
filled.data$day <- factor(filled.data$day)
filled.data$interval <- factor(filled.data$interval)
weeksteps <- aggregate(steps~interval+day, filled.data, mean)
ggplot(data=weeksteps, aes(interval,steps, group = 1)) + geom_line() + facet_grid(rows = ~day)
```